version: '3.9'

services:
  app:
    build: .
    entrypoint: ["sh", "./.docker/entrypoint.sh"]
    container_name: alertaai-api
    ports:
      - 3004:3004
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: db
    ports:
      - 5438:5432
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alertaai
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
   